name: app_deia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  camera: ^0.11.0+2
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.2.2
  http_parser: ^4.0.2
  just_audio: ^0.9.42
  mime: ^2.0.0
  path: ^1.9.0
  path_provider: ^2.1.4
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
